config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: [:create, :new, :index, :show] do
  resources :reviews, only: [:new, :create]
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, :dependent => :destroy

  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"].freeze
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, :content, presence: true
  validates :rating, inclusion: { in: (0..5), allow_nil: false }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_action :set_restaurant, only: [:show]
  def new
  @restaurant = Restaurant.new
  end

  def index
  @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path(@restaurant)
  end

  def show
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li> <%= link_to restaurant.name, restaurant_path(restaurant.id)%></li>
  <% end %>
</ul>

<%= link_to  "add new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
   <%= f.input :address%>
   <%= f.input :phone_number%>
  <%=  f.input :category%>
  <%= f.submit "Submit Restaurant", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back to Restaurants", restaurants_path %>

app/views/restaurants/show.html.erb
<div class="container my-1 mx-5">
  <h1><%= @restaurant.name %></h1>
  <div class="bg-light p-3 border mt-3">
    <p class="fs-2 "><%= @restaurant.address %></p>
  </div>
  <div class="row mt-3">
    <%= link_to "Back", restaurants_path %>
    <%= link_to "Edit this task", restaurant_path(@restaurant) %>
    <%= link_to "delete this task", restaurant_path(@restaurant),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </div>
</div>